enum PVEZ_RPC {
	UPDATE_CONFIG = 48102075,
	UPDATE_ZONES,
	UPDATE_BOUNTIES,

	UPDATE_STATUS_ON_CLIENT,
	NOTIFICATION_PERSONAL,
	NOTIFICATION_SERVERWIDE,
	
	UPDATE_LAWBREAKERS_MARKERS,
	UPDATE_LAWBREAKER_STATUS,
	
	ADMIN_ACCESS_REQUEST,
	ADMIN_LAWBREAKERS_DATA_REQUEST,
	ADMIN_ZONES_DATA_REQUEST,
	ADMIN_BOUNTIES_DATA_REQUEST,
	ADMIN_UPDATE_LAWBREAKERS
}

enum PVEZ_NotificationType {
	NOTIF_GENERIC = 0,
	NOTIF_ZONE_ENTER,
	NOTIF_ZONE_EXIT,
	NOTIF_EXIT_COUNTDOWN,
	NOTIF_LB_PERSONAL,
	NOTIF_LB_SERVERWIDE
}